version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://studentuser:studentpass@db:5432/studentdb
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - db

volumes:
  postgres_data: