name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'config/**'
      - 'Dockerfile'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'config/**'
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8

    - name: Build API
      run: make migrate

    - name: Run tests and linting
      run: make test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_TOKEN }}

    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}/student-crud
        DOCKER_IMAGE_VERSION: ${{ github.sha }}
      run: |
        docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION .
        docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION